### ISSUE TITLE
The connection is successful, but there is no output, and there is no message in echo ping. What is the reason?

### ISSUE THREAD

**Issue by CHANdaFeng** [GSO-soslab/sonar_oculus#1]
Hello, the model I use is m1200d. When I use sonar_oculus.launch, I can connect, but run to sonar.cpp262 line of code if (nbeams > 0 && nbins > 0 && id > latest_id) {
latest_id = id;
There is no output, and echo ping has no message, what is the reason?

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.15.15
 * /sonar_oculus_node_M1200d/frame: /M1200d
 * /sonar_oculus_node_M1200d/model: M1200d

NODES
  /
    sonar_oculus_node_M1200d (sonar_oculus/sonar_oculus_node)

ROS_MASTER_URI=http://localhost:11311

process[sonar_oculus_node_M1200d-1]: started with pid [231359]
[ INFO] [1678084730.071438304]: Initializing...
[ INFO] [1678084730.084533767]: Connecting...
[ INFO] [1678084730.085274067]: The IP address is 169.254.70.29
[ INFO] [1678084730.085303625]: Oculus model is M1200d
[ INFO] [1678084730.085783393]: Connected!
[ INFO] [1678084730.086022395]: Got param: /M1200d

**Comment by 17773344961** [comment]
Have you solved this problem? I meet the same problem now and can't find out the reason

**Comment by linzha0** [comment]
you can try the new driver: https://github.com/GSO-soslab/blueprint_oculus_sonar

**Comment by 17773344961** [comment]
> you can try the new driver: https://github.com/GSO-soslab/blueprint_oculus_sonar

Thank you very much for your reply! I modified the line #317 in the document "OculusClient.cpp" as "int bytesAvailable", and then the problem have been solved!
