### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by WaHa-World** [GSO-soslab/sonar_oculus#3]
When I execute catkin build cv_bridge, I get no reaction. What might be the reason? Thank you!

**Comment by linzha0** [comment]
if you were Ubuntu 20.04, no need to build cv_bridge. However, this driver has a socket issue in Ubuntu 20.04. We are working on a new driver and will release it soon.

**Comment by WaHa-World** [comment]
Thank you.



---Original---
From: "Lin ***@***.***&gt;
Date: Thu, Oct 12, 2023 22:46 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [GSO-soslab/sonar_oculus] build problem (Issue #3)




 
if you were Ubuntu 20.04, no need to build cv_bridge. However, this driver has a socket issue in Ubuntu 20.04. We are working on a new driver and will release it soon.

**Comment by linzha0** [comment]
You can take a look at another driver from UW-APL: https://gitlab.com/apl-ocean-engineering/oculus_sonar_driver
